### ISSUE TITLE
Moodboard - finding our flow

### ISSUE THREAD

**Issue by goug0035** [shakeel-nazir/simple-chat-app#2]
everyone post ur moodboard

**Comment by ashtastic** [comment]
The Awkward Chat or The Bad News Communicator (possible names... open to others)

It is a chat that you send to someone in order to tell them uncomfortable/bad news.

Ideas:
- http://answerthepublic.com/
- video in background of someone unimpressed
- a colour scheme that is the COMPLETE opposite of bad (pink, fluffy clouds) — antagonizing. 
- glitter around words that are bad or around swear words to make them "look" more positive.
